name: Build Android APK
on:
  push:
    branches: [ mobile-app ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        working-directory: mobile
        run: npm install --legacy-peer-deps

      - name: Prebuild Expo to generate Android folder
        working-directory: mobile
        run: npx expo prebuild --clean

      - name: Build APK (Assemble Release)
        working-directory: mobile/android
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/android/app/build/outputs/apk/release/app-release.apk
